### ISSUE TITLE
Tables with a "." in the name wreck havoc with the system

### ISSUE THREAD

**Issue by pramsey** [CartoDB/CartoDB-SQL-API#224] opened 2015-05-25 16:52 UTC
A user <https://cartodb.supportbee.com/tickets/5393575#> managed to create a table in their account, probably using FME, that had a "." in the name. (You can do it too, just CREATE TABLE "foo.bar" and you'll get one.) Once that was done, other attempts to create new tables, even ones with nice names, started failing.

FME would from then on fail, and say things like:
```
CARTODB writer: HTTP Error 400-599: HTTP error code : 400
CARTODB writer: Error returned by server : cross-database references are not implemented: "public.gis.v_lds_primary_parcel_title_owner"
CARTODB writer: Unable to locate or open account 'les-cochran'. Please ensure the account exists and is accessible. Note that the CARTODB writer does not have the ability to create a new account. However, creating the account manually in advance allows for subsequent data insertion
A fatal error has occurred. Check the logfile above for details
A fatal error has occurred. Check the logfile above for details
```
Note the funny name of the table the SQL API is complaining about. Perhaps the security subsystem is concatenating the names of tables with schema names, and not quoting things, so the database ends up being handed a "full-qualified" name that actually has two "schemas" in it? Since PgSQL supports fairly arbitrary (quotes) identifiers, a more rigorous use of "" in all client code might be required to erase these kinds of issues.

**Comment by GarbageBear** [comment] 2015-06-10 15:13
I am experiencing a similar issue after creating a table 'public.ry.test.dots'.

After the initial table creation seems to succeed it poisons the rest of the datasets such that future requests for the user table list return the error. Additionally, the CartoDB webUI does not show the table in the list of datasets so removing it is challenging.

Query: 'SELECT CDB_UserTables()'
Error: 'improper relation name (too many dotted names): public.ry.test.dots'

**Comment by SigTill** [comment] 2015-07-02 07:55
Same experience on FME2016. Also submitted to Safe Software if they can implement some more error-checking: https://twitter.com/SigTill/status/616515330668670976

**Comment by kenatsafe** [comment] 2015-07-03 11:56
At Safe we have raised PR#61958 for this issue but we'd prefer not prevent "."  on the assumption this will eventually work properly.

**Comment by javisantana** [comment] 2015-07-07 10:14
but is this a issue with SQL API or with the editor. I can create and query tables with dots and then query them with the SQL API.

What is the queries being sent from FME?

**Comment by pramsey** [comment] 2015-07-07 12:55
FME works strictly through the SQL API.

**Comment by rochoa** [comment] 2015-09-03 11:18
I added a regression test yesterday and after merging a new feature from https://github.com/CartoDB/CartoDB-SQL-API/pull/247 it started to fail.

I just created https://github.com/CartoDB/cartodb-postgresql/issues/133 to fix `CDB_QueryTables` so it returns properly quoted names when necessary.

I'm reopening this issue until https://github.com/CartoDB/cartodb-postgresql/pull/134 gets merged into master.

**Closed** 2015-09-07 15:10 UTC
Labels: bug

**Comment by TheDorkKnight** [comment] 2015-10-01 23:40
This issue seems to be exhibited from the CDB_CartoDBfy() function as well.

Here are some experimental results:

# Table Creation

#### SQL
`CREATE TABLE "tablewithdot.uhoh" ( cartodb_id SERIAL,the_geom GEOMETRY(GEOMETRY, 4326), the_geom_webmercator GEOMETRY(GEOMETRY, 3857),"num" FLOAT8,PRIMARY KEY (cartodb_id) );DROP SEQUENCE IF EXISTS "tablewithdot.uhoh_cartodb_id_seq" CASCADE;CREATE SEQUENCE "tablewithdot.uhoh_cartodb_id_seq" START 1;ALTER TABLE "tablewithdot.uhoh" ALTER COLUMN cartodb_id SET DEFAULT nextval('"tablewithdot.uhoh_cartodb_id_seq"')`

#### Response
empty (no news is good news in these queries).

# CDB_CartoDBfy() attempts

***
### CartoDBfy SQL Default GDAL Behaviour:
***

#### SQL
`SELECT cdb_cartodbfytable('tablewithdot.uhoh')`

#### Response
`{"error":["schema \"tablewithdot\" does not exist"]}`

***
### CartoDBfy SQL With Quoted Table Name:
***

#### SQL
`SELECT cdb_cartodbfytable("tablewithdot.uhoh")`
	
#### Response
`{"error":["column \"tablewithdot.uhoh\" does not exist"]}`

***
### CartoDBfy SQL With Quoted Table Name and Schema:
***

#### SQL
`SELECT cdb_cartodbfytable("public", "tablewithdot.uhoh")`

#### Response
`{"error":["column \"public\" does not exist"]}`

***
### CartoDBfy SQL With Quoted Table Name and Text Schema: (should be same as not supplying schema)
***

#### SQL
`SELECT cdb_cartodbfytable('public', "tablewithdot.uhoh")`
	
#### Response
`{"error":["column \"tablewithdot.uhoh\" does not exist"]}`

**Comment by pramsey** [comment] 2015-10-01 23:43
None of the examples with double quotes really make sense, since they won't be evaluated as strings, but as regclass lookups. And the first example legitimately cannot find the non-existing schema that is referenced. A construction I would expect to work would be `cdb_cartodbfytable('"tablewithdot.uhoh"')`, but heaven help me...

**Comment by TheDorkKnight** [comment] 2015-10-01 23:47
Ha, I suppose I should have thought of that. I'll give it a try.

**Comment by TheDorkKnight** [comment] 2015-10-02 00:06
`SELECT cdb_cartodbfytable('"tablewithdot.uhoh"')`

gives me

`{"error":["cross-database references are not implemented: \"public.tablewithdot.uhoh\""]}`

while

`SELECT cdb_cartodbfytable('"public"', '"tablewithdot.uhoh"')`

gives me

`{"error":["Invalid schema name \"\"public\"\""]}`
