### ISSUE TITLE
table cache timeout

### ISSUE THREAD

**Issue by calvinmetcalf** [CartoDB/CartoDB-SQL-API#244] opened 2015-08-05 12:22 UTC
the timeout of LRU (as used [here](https://github.com/CartoDB/CartoDB-SQL-API/blob/91afe720bca596869b98404538929671af60a7d1/app/controllers/app.js#L74)) is maxAge since last accessed, not since set.  If your aware then carry on, but this has led to some subtle bugs when I assumed it worked the other way.

**Comment by rafatower** [comment] 2017-06-27 08:42
Sorry for getting back to you so late.

I just confirmed the issue by executing this small test:
```js
// file stale-lru-entry-test.js
var LRU = require("lru-cache");

var tableCache = LRU({
    max: 8192,
    maxAge: 1000*3 // 3 seconds
});

tableCache.set("foo", "bar");

(function() {
    var iter = 1;
    var timeout = setInterval(function() {
        // Get value for "foo" every seconds, up to 5 times
        console.log("iter = " + iter + "; tableCache.get(\"foo\") = " + tableCache.get("foo"));
        iter++;
        if(iter > 5) {
            clearInterval(timeout);

            // Execute after 3.5 seconds
            setTimeout(function() {
                console.log("tableCache.get(\"foo\") = " + tableCache.get("foo"));
            }, 3500);

        }
    }, 1000);
})();
```

and this is the output:
```
$ node stale-lru-key-test.js
iter = 1; tableCache.get("foo") = bar
iter = 2; tableCache.get("foo") = bar
iter = 3; tableCache.get("foo") = bar
iter = 4; tableCache.get("foo") = bar
iter = 5; tableCache.get("foo") = bar
tableCache.get("foo") = undefined
```

We're using a rather old version of the `lru-cache` dependency. I'll check if upgrading could help.

Thanks a lot for reporting.

cc'ing @rochoa for awareness

**Comment by rafatower** [comment] 2017-06-27 09:34
A possibility would be to replace `get` calls by `peek`. See https://github.com/isaacs/node-lru-cache/#api

**Comment by rafatower** [comment] 2017-06-28 08:52
After considering it, we disabled the LRU cache by default. See https://github.com/CartoDB/CartoDB-SQL-API/issues/422

It can yet be re-enabled by configuration. Just change the value `tableCacheEnabled` from `false` to `true` in the [configuration](https://github.com/CartoDB/CartoDB-SQL-API/blob/d2f18849992a4edbc0ebc15e6b5c4f05aa4d40b3/config/environments/development.js.example#L84)

We plan to fully remove the LRU cache, so this kind of addresses your issue from the root cause. I'm closing it FTM. Feel free to reopen if you have doubts or concerns or want to further discuss it.

**Closed by rafatower** 2017-06-28 08:52 UTC
