### ISSUE TITLE
503 error because of large rows

### ISSUE THREAD

**Issue by iriberri** [CartoDB/CartoDB-SQL-API#210] opened 2015-02-28 15:38 UTC
From Support SB/4654450:

Exporting a table as GeoJSON is raising the error:

````
Error 503 Service Unavailable

Service Unavailable

Guru Meditation:

XID: 847594683

Varnish cache server
````

If we apply an "offset 1" to the query, which is returning 2 rows, it says:

```
{
error: [
"Row too large, was 8009137 bytes"
]
}
````

**Comment by rochoa** [comment] 2015-02-28 16:05
They are probably two different issues.

The first one is probably because of the response taking too long. What is the query or how much does it take to execute / starts to return the response?

The `"Row too large, was 8009137 bytes"` is a configuration limit that I just removed until we decide what's the appropriate value.

**Comment by zenitraM** [comment] 2015-02-28 16:08
If you request over v1, the request works but gets stalled after the first row is served.
It seems that the issue is the limit not closing the request if the second row is too large, causing Varnish to timeout

**Comment by rochoa** [comment] 2015-05-13 16:54
This was related to @zenitraM's comment and it was fixed in https://github.com/CartoDB/CartoDB-SQL-API/pull/222

**Closed by rochoa** 2015-05-13 16:54 UTC
