### ISSUE TITLE
queries with functions are being cached

### ISSUE THREAD

**Issue by javisantana** [CartoDB/CartoDB-SQL-API#238] opened 2015-07-28 08:56 UTC
```
/api/v2/sql?q=select%20cdb_usertables()
```

is being cached and it should not

**Comment by rochoa** [comment] 2015-09-02 13:49
This is the same as https://github.com/CartoDB/CartoDB-SQL-API/issues/157

We need to decide either we use the `{db_name}:table` x-cache-channel header or we just don't set a x-cache-channel header at all. This is not an easy decision as some times when calling a function you might want to hit the cache but most of the time you don't want to.

Considering most of the time knowing what are the involved tables while behind a function would not be possible **I propose to not add x-cache-channel header if we are not able to guess at least one table**. Furthermore, using the `{db_name}:table` workaround means:
 1. Any table modification will invalidate all cached requests using `{db_name}:table` x-cache-channel header.
 1. User needs to know that design gotcha and have a table to do an insert/update so her cached requests are invalidated due to the workaround. I don't like to leak/expose that hack to the users.

**Comment by rochoa** [comment] 2015-09-02 13:50
Once we decide and close this issue, this will fix #157.

**Comment by javisantana** [comment] 2015-09-07 15:24
Sounds good for me, specially since we will be removing x-cache-channel

For the future we need to have some kind of table that maps functions to tables so we can have caching for functions.

In any case caching a immutable function should be safe, right?

**Comment by rochoa** [comment] 2015-09-07 15:31
Yes, we could cache inmutable functions but still we have to know when a query involves just an immutable function. Do you you if that's possible?

**Comment by javisantana** [comment] 2015-09-07 15:42
everything is possible :) the thing here is if setting the right cache headers varnish is going to do its job cc @zenitraM

**Comment by andrewbt** [comment] 2015-11-24 19:25
I have a user claiming (and I can confirm on my own account) that when they use CDB_UserTables() in a SQL API request, the results are being cached for about 10 minutes. From them:

=====
Using the SQL API (https://username.cartodb.com/api/v2/sql?api_key=keykeykeykey&q=SELECT+CDB_UserTables()) you may get the list of names of available tables(datasets).

But when a user has created a new dataset, the SQL API query above do not include the newly created dataset in its return. It seems that the query is being cached for about 10mins.
=====

I was able to get the URL to return the recently created dataset by adding a cache buster ( _https://username.cartodb.com/api/v2/sql?api_key=keykeykeykey&q=SELECT+CDB_UserTables()&cachebuster=randomstring_ ). But I'm inclined to think maybe this issue isn't yet resolved? @javisantana @rochoa comments?

**Comment by rochoa** [comment] 2015-11-24 20:41
It was closed because it got merged to master but it never got released, I will take care of that tomorrow.

**Comment by rochoa** [comment] 2015-11-26 18:06
Didn't have time to work on this, and I won't be able to work on this until next week.

**Comment by rochoa** [comment] 2016-01-28 16:31
This is live.

**Comment by danicarrion** [comment] 2016-07-29 16:45
could it be this is a problem again? At least CDB_UserTables is being cached again (tested onprem 1.2.1 and 1.3.0). code has changed a lot since this patch was created so it's hard for me to understand if the patch is still doing its job.

**Comment by rochoa** [comment] 2016-08-01 09:24
What is the SQL API version those on-prem versions have?

We had a regression were tables were tagged to be cached: https://github.com/CartoDB/CartoDB-SQL-API/pull/330. Functions were OK. The regression was introduced in version 1.26.0 and was fixed in 1.34.0.

**Closed by rochoa** 2016-08-01 09:24 UTC

**Comment by danicarrion** [comment] 2016-08-01 10:21
Onprem 1.3.0 has 1.29.1
