### ISSUE TITLE
copyfrom stuck and locks table

### ISSUE THREAD

**Issue by alrocar** [CartoDB/CartoDB-SQL-API#579] opened 2019-04-01 12:06 UTC
**Problem**

We are starting to extensively use the COPY API in CARTOframes. While developing the new `write` method that uses `copyfrom` behind the scenes I've found a case in which the COPY statement gets stuck in the user database, locking the table.

I'm using this query to list the processes with Exclusive Lock in my team user database:

```
SELECT pg_stat_activity.pid,
       pg_class.relname,
       pg_locks.transactionid,
       pg_locks.granted,
       substr(pg_stat_activity.query,1,30) AS query_snippet,
       age(now(),pg_stat_activity.query_start) AS "age"
FROM pg_stat_activity,
     pg_locks
LEFT OUTER JOIN pg_class ON (pg_locks.relation = pg_class.oid)
WHERE pg_locks.pid=pg_stat_activity.pid
  AND pg_locks.mode = 'ExclusiveLock'
ORDER BY query_start;
```

The result is:

```
pid  | relname | transactionid | granted |         query_snippet          |          age
-------+---------+---------------+---------+--------------------------------+------------------------
 21393 |         |               | t       | COPY cf_test_table_3_7_none_no | 2 days 23:18:34.335634
```

I've checked I cannot do any operation on the table other than terminate the process with `SELECT pg_terminate_backend(pid);`

**How to reproduce**

I've uploaded a CARTOframes branch with a test that reproduces the problem. To test it:

```
git clone https://github.com/CartoDB/cartoframes
cd cartoframes
git checkout 561_copyfrom_write_copy_bug
python3 -m venv env
source env/bin/activate
pip install -r requirements.txt
pip install -e .
pip install pytest
cp test/secret.json.sample test/secret.json #and introduce your CARTO credentials in the secret.json file
py.test -s test/test_context.py::TestCartoContext::test_cartocontext_write_lnglat
```

After the test fails with this error `carto.exceptions.CartoException: local variable 'the_geom_val' referenced before assignment` the COPY statement should be stuck in your user database and you have to manually kill it to be able to do any other operation on the related table.

**Note**: I've realized of this while developing this new feature, that has a bug in it: a variable being used before it's declared in the rows streaming function. But I'd like to highlight the importance of this, since it appears that any bug introduced on the call to the `copyfrom` API may left the related table unusable.

**Note 2**: While checking the process that locked a table, I've realized I had other statements apparently from our Import API? (so this might not be an isolated case...)

```
  4983 |         |     508570110 | t       | COPY "cdb_importer"."importer_ | 3 days 19:00:21.72226
  4983 |         |               | t       | COPY "cdb_importer"."importer_ | 3 days 19:00:21.72226
```

cc. @CartoDB/rt-managers for triage

cc. @oleurud for awareness

**Comment by oleurud** [comment] 2019-04-08 19:56
I can not reproduce it :scream:

**Comment by oleurud** [comment] 2019-04-08 21:01
Ok, finally I have reproduced it, it is happening randomly. I am trying to create a test

**Comment by alrocar** [comment] 2019-05-08 15:04
Great!

I wanted to mention that this issue happened specifically with the branch of CARTOframes I mentioned in the issue (`561_copyfrom_write_copy_bug`)

Could you rebuild that specific branch in CI while running the script?

**Comment by dgaubert** [comment] 2019-05-08 15:41
> I wanted to mention that this issue happened specifically with the branch of CARTOframes I mentioned in the issue (561_copyfrom_write_copy_bug)

What has that branch changed?

**Comment by alrocar** [comment] 2019-05-08 16:01
It contains a bug in the client code ([a variable used before it's initialized](https://github.com/CartoDB/cartoframes/commit/18ceeb6cda72649fe6656b474e1fde5d726ec8fb#diff-9c45bf459be12218d26e264077e1f4f3R338)) that made the COPY queries to get stuck in the server.

The bug is quite explicit but it served to test the stuck behaviour when there's an error client side.

**Comment by dgaubert** [comment] 2019-05-09 15:28
I've been debugging this issue along @oleurud, I've been able to reproduce the problem. The issue is related to the [method that generates the CSV](https://github.com/CartoDB/cartoframes/blob/62b4ce93bc90d077f08fe9bc2d5e9ec6eb14abad/cartoframes/context.py#L320-L346) to be sent with the `copyfrom` endpoint. The generator is [raising an exception](https://travis-ci.org/CartoDB/cartoframes/jobs/530191678#L756), and the underlying HTTP client is not handling that exception properly (it might be the "iterable" must not raise an error). At this point, the HTTP connection remains open indefinitely in SQL_API (and Postgres) waiting for the data that never arrives. So in the database, the copy command seems to be stuck, but it's waiting for the streamed data forever. As we are running CartoFrames' tests in Travis CI, it creates a VM. Then it runs the test and, when done it destroys the VM. If CartoFrames is not closing the connection, it should be destroyed when the VM no longer exits. The fun fact is the HTTP connection remains open between SQL-API and user's  database :scream:. 

So I'm focusing on Nginx, which is the piece of software between CartoFrames and SQL-API. It might Nginx is keeping the connection although the client doesn't exist anymore. I've just asked for help to @gonzalosr  in case he can shed some light here.

The following is a small diagram to clarify the use case:

1) TravisCI runs a job build
```
 --------------         ---------------------------------------------- 
| TravisCI VM  |       |                   CARTO                      |
| ------------ |       | -------         ---------         ---------- |
||            ||       ||       |       |         |       |          ||
|| CartoFames || <===> || Nginx | <===> | SQL API | <===> | Postgres ||
||            ||       ||       |       |         |       |          ||
| ------------ |       | -------         ---------         ---------- |
 --------------         ----------------------------------------------
```
2) When the job finishes, the VM is drestoyed and the connection to Nginx should be destroyed as well
```
--------------         ---------------------------------------------- 
| TravisCI VM  |       |                   CARTO                      |
| ------------ |       | -------         ---------         ---------- |
||            ||       ||       |       |         |       |          ||
|| CartoFames ||   X   || Nginx | <===> | SQL API | <===> | Postgres ||
||            ||       ||       |       |         |       |          ||
| ------------ |       | -------         ---------         ---------- |
 --------------         ----------------------------------------------
```
3) As the conection between SQL-API and Postgres remains active, I guess Nginx is not closing the connection:
```
                        ---------------------------------------------- 
                       |                   CARTO                      |
                       | -------         ---------         ---------- |
                       ||       | ????? |         |       |          ||
                       || Nginx | <===> | SQL API | <===> | Postgres ||
                       ||       |       |         |       |          ||
                       | -------         ---------         ---------- |
                        ----------------------------------------------
```

These are my finding so far.

**Comment by gonzalosr** [comment] 2019-05-09 16:03
Hey @dgaubert, @dppascual is going to take a look at this as he is in RT now 🤗

**Comment by dppascual** [comment] 2019-05-13 16:33
## Additional info about how nginx works

A typical HTTP request processing cycle looks like the following:

1. Client sends HTTP request.
2. Process header.
3. Process body.
4. Run through the processing phases.

When nginx handles an HTTP request, it passes it through a number of processing phases. At each phase there might be 0 or more handlers to call. Here is a list of all phases:

* NGX_HTTP_SERVER_REWRITE_PHASE — the phase of request URI transformation on virtual server level;
* NGX_HTTP_FIND_CONFIG_PHASE — the phase of configuration location lookup;
* NGX_HTTP_REWRITE_PHASE — the phase of request URI transformation on location level;
* NGX_HTTP_POST_REWRITE_PHASE — request URI transformation post-processing phase;
* NGX_HTTP_PREACCESS_PHASE — access restrictions check preprocessing phase;
* NGX_HTTP_ACCESS_PHASE — access restrictions check phase;
* NGX_HTTP_POST_ACCESS_PHASE — access restrictions check post-processing phase;
* NGX_HTTP_TRY_FILES_PHASE — try_files directive processing phase;
* NGX_HTTP_CONTENT_PHASE — content generation phase;
* NGX_HTTP_LOG_PHASE — logging phase.

When the HTTP request header is read, nginx does a lookup of the associated virtual server configuration. If the virtual server is found, the request goes through six phases:

1. server rewrite phase
2. location phase
3. location rewrite phase (which can bring the request back to the previous phase)
4. access control phase
5. try_files phase
6. log phase

In an attempt to generate the necessary content in response to the request, nginx passes the request to a suitable content handler. In our case, `proxy-pass` handler is called. 

The content handlers' content is then passed to the filters (not when a `proxy-pass` handler is set up). Filters do the task of manipulating the output produced by a handler. Filters follow a particular design pattern. A filter gets called, starts working, and calls the next filter until the final filter in the chain is called. After that, nginx finalizes the response. Filters don't have to wait for the previous filter to finish. The next filter in a chain can start its own work as soon as the input from the previous one is available (functionally much like the Unix pipeline). In turn, the output response being generated can be passed to the client before the entire response from the upstream server is received. Examples of body filters that are used:

* gzip compression
* chunked encoding

After the filter chain, the response is passed to the writer.

Upstreams are used to implement what can be identified as a content handler which is a reverse proxy (proxy_pass handler). Upstream modules mostly prepare the request to be sent to an upstream server (or "backend") and receive the response from the upstream server. There are no calls to output filters here. What an upstream module does exactly is set callbacks to be invoked when the upstream server is ready to be written to and read from. Callbacks implementing the following functionality exist:

* Crafting a request buffer (or a chain of them) to be sent to the upstream server
* Re-initializing/resetting the connection to the upstream server (which happens right before creating the request again)
* Processing the first bits of an upstream response and saving pointers to the payload received from the upstream server
* Aborting requests (which happens when the client terminates prematurely) --> **This callback should be closed the upstream connection. Anyway, if this connection is not closed when the callback is triggered, it will be done when the timeout (proxy_read_timeout) comes up.**
* Finalizing the request when nginx finishes reading from the upstream server
* Trimming the response body (e.g. removing a trailer)

## Nginx timeouts

**From client side**

`keepalive_timeout   60` --> a timeout during which a keep-alive client connection will stay open on the server side.

**From upstream side**

`proxy_connect_timeout 60s` --> Defines a timeout for establishing a connection with a proxied server.

`proxy_read_timeout 120s` --> Defines a timeout for reading a response from the proxied server. The timeout is set only between two successive read operations, not for the transmission of the whole response. If the proxied server does not transmit anything within this time, the connection is closed.

 `proxy_send_timeout 60s` --> Sets a timeout for transmitting a request to the proxied server. The timeout is set only between two successive write operations, not for the transmission of the whole request. If the proxied server does not receive anything within this time, the connection is closed.

Nginx uses event notification mechanisms like `epoll` for handling a variety of actions associated with managing network connections and content retrieval so that I'm not sure if the connection is closed during the `aborting request` callback. Looking at nginx code:

1. In the function `ngx_http_upstream_init_request`, when the directive `proxy_ignore_client_abort` is enabled, nginx will not check for client connection. In our config, such directive is set to its default value `off` so that the client connection is checked out: 

```
    if (!u->store && !r->post_action && !u->conf->ignore_client_abort) {
        r->read_event_handler = ngx_http_upstream_rd_check_broken_connection;
        r->write_event_handler = ngx_http_upstream_wr_check_broken_connection;
    }
```

2. Later on, when reading the body from upstream and writing to downstream, if client closed the connection the flag `p->downstream_error` is set to 1. 

3. In `ngx_http_upstream_process_request`, if `downstream_error` flag is set, we also close the connection to upstream: 

```
    if (p->downstream_error) {
        ngx_log_debug0(NGX_LOG_DEBUG_HTTP, r->connection->log, 0,
                       "http upstream downstream error");

        if (!u->cacheable && !u->store && u->peer.connection) {
            ngx_http_upstream_finalize_request(r, u, NGX_ERROR);
        }
    }
```

This code shows up how the request is processed when the client closes the connection and nginx tries to send data from upstream to downstream. In other situation, when no data is sent, timeouts come up and, hence, nginx should close connections.

cc. @oleurud @dgaubert All this explanation is theoretical and based on the code that I have checked out, so in order to confirm and clarify this situation, can we test it in staging? In production, it could be a nightmare due to the amount of connections that nginx could handle.

**Comment by dgaubert** [comment] 2019-05-29 10:26
Fix implemented in #588, #589, and #590

**Comment by dgaubert** [comment] 2019-05-30 13:24
Fixed in production already!

**Closed by dgaubert** 2019-05-30 13:24 UTC
Labels: Node.js, rt-backend

**Comment by alrocar** [comment] 2019-05-30 13:29
❤️
